name: Build YGOPro (Win32 Release)

on:
  push:
    branches: [ yml ]
  pull_request:
    branches: [ yml ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Download DirectX SDK
      if: matrix.nodxsdk != true && steps.dxsdk.outputs.cache-hit != 'true'
      id: dxsdk-download
      uses: mercury233/action-cache-download-file@v1.0.0
      with:
        url: https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe

    - name: Install DirectX SDK
      if: matrix.nodxsdk != true && steps.dxsdk.outputs.cache-hit != 'true'
      run: |
        7z x ${{ steps.dxsdk-download.outputs.filepath }} -aoa

    - name: Set DirectX SDK environment variable
      if: matrix.nodxsdk != true
      run: |
        $dxsdkPath = Resolve-Path 'DXSDK'
        "DXSDK_DIR=$($dxsdkPath.ProviderPath)\" | Out-File -FilePath $env:GITHUB_ENV -Append
    
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Initialize submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote

    # Download and extract dependencies
    - name: clone dependency
      run: |
        git clone --depth 1 https://github.com/vgdpro/vgdpro-dependency.git dependency
        xcopy /E /Y /Q dependency\* .

    # Prepare build environment
    - name: Copy premake files
      run: xcopy /E /Y /Q premake\* .

    # Generate solution
    - name: Generate Visual Studio solution
      run: |
        .\premake5.exe vs2022

    # Build solution
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution (Win32 Release)
      run: |
        MSBuild.exe build/YGOPro.sln /m /p:Configuration=Release /p:Platform=Win32
        
    # Upload artifacts
    - name: Verify build output
      run: dir bin/Release /s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro-Win32-Release
        path: bin/Release/YGOPro.exe
        if-no-files-found: error